services:
  database:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vue-monitor
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge
